#
# Copyright 2025 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""
Sandbox model converter utilities.

Provides conversion functions between API models and domain models,
similar to the Kotlin SDK SandboxModelConverter.

This converter is designed to work with openapi-python-client generated models,
which use attrs for model definitions.
"""
from datetime import datetime, timedelta, timezone

from opensandbox.api.lifecycle.models import (
    CreateSandboxResponse,
    Endpoint,
    ListSandboxesResponse,
    RenewSandboxExpirationRequest,
    RenewSandboxExpirationResponse,
    Sandbox,
)
from opensandbox.api.lifecycle.models import (
    PaginationInfo as ApiPaginationInfo,
)
from opensandbox.api.lifecycle.models import (
    SandboxStatus as ApiSandboxStatus,
)
from opensandbox.api.lifecycle.models.create_sandbox_request import CreateSandboxRequest
from opensandbox.api.lifecycle.models.image_spec import ImageSpec
from opensandbox.models.sandboxes import (
    NetworkPolicy,
    PagedSandboxInfos,
    PaginationInfo,
    SandboxCreateResponse,
    SandboxEndpoint,
    SandboxImageSpec,
    SandboxInfo,
    SandboxRenewResponse,
    SandboxStatus,
    Volume,
)


class SandboxModelConverter:
    """
    Sandbox model converter utilities.

    Provides static methods to convert between API models and domain models,
    following the pattern from the Kotlin SDK.

    The API models are generated by openapi-python-client and use attrs,
    while domain models are standard Python dataclasses/classes.
    """

    @staticmethod
    def to_api_image_spec(spec: SandboxImageSpec) -> ImageSpec:
        """Convert domain SandboxImageSpec to API ImageSpec."""
        from opensandbox.api.lifecycle.models.image_spec import ImageSpec
        from opensandbox.api.lifecycle.models.image_spec_auth import ImageSpecAuth
        from opensandbox.api.lifecycle.types import UNSET

        auth = UNSET
        if spec.auth:
            auth = ImageSpecAuth(
                username=spec.auth.username,
                password=spec.auth.password,
            )

        return ImageSpec(
            uri=spec.image,  # API uses 'uri', domain uses 'image'
            auth=auth,
        )

    @staticmethod
    def to_api_volume(volume: Volume):
        """Convert domain Volume to API Volume."""
        from opensandbox.api.lifecycle.models.host import (
            Host as ApiHost,
        )
        from opensandbox.api.lifecycle.models.ossfs import (
            OSSFS as ApiOSSFS,
        )
        from opensandbox.api.lifecycle.models.ossfs_version import OSSFSVersion
        from opensandbox.api.lifecycle.models.pvc import (
            PVC as ApiPVC,
        )
        from opensandbox.api.lifecycle.models.volume import Volume as ApiVolume
        from opensandbox.api.lifecycle.types import UNSET

        api_host = UNSET
        if volume.host is not None:
            api_host = ApiHost(path=volume.host.path)

        api_pvc = UNSET
        if volume.pvc is not None:
            api_pvc = ApiPVC(claim_name=volume.pvc.claim_name)

        api_ossfs = UNSET
        if volume.ossfs is not None and volume.ossfs.access_key_id is not None and volume.ossfs.access_key_secret is not None:
            api_ossfs = ApiOSSFS(
                bucket=volume.ossfs.bucket,
                endpoint=volume.ossfs.endpoint,
                access_key_id=volume.ossfs.access_key_id,
                access_key_secret=volume.ossfs.access_key_secret,
                version=OSSFSVersion(volume.ossfs.version),
                options=volume.ossfs.options if volume.ossfs.options is not None else UNSET,
            )

        api_sub_path = UNSET
        if volume.sub_path is not None:
            api_sub_path = volume.sub_path

        return ApiVolume(
            name=volume.name,
            mount_path=volume.mount_path,
            read_only=volume.read_only,
            host=api_host,
            pvc=api_pvc,
            ossfs=api_ossfs,
            sub_path=api_sub_path,
        )

    @staticmethod
    def to_api_create_sandbox_request(
        spec: SandboxImageSpec,
        entrypoint: list[str],
        env: dict[str, str],
        metadata: dict[str, str],
        timeout: timedelta | None,
        resource: dict[str, str],
        network_policy: NetworkPolicy | None,
        extensions: dict[str, str],
        volumes: list[Volume] | None,
    ) -> CreateSandboxRequest:
        """Convert domain parameters to API CreateSandboxRequest."""
        from opensandbox.api.lifecycle.models.create_sandbox_request import (
            CreateSandboxRequest,
        )
        from opensandbox.api.lifecycle.models.create_sandbox_request_env import (
            CreateSandboxRequestEnv,
        )
        from opensandbox.api.lifecycle.models.create_sandbox_request_extensions import (
            CreateSandboxRequestExtensions,
        )
        from opensandbox.api.lifecycle.models.create_sandbox_request_metadata import (
            CreateSandboxRequestMetadata,
        )
        from opensandbox.api.lifecycle.models.network_policy import (
            NetworkPolicy as ApiNetworkPolicy,
        )
        from opensandbox.api.lifecycle.models.network_policy_default_action import (
            NetworkPolicyDefaultAction,
        )
        from opensandbox.api.lifecycle.models.network_rule import (
            NetworkRule as ApiNetworkRule,
        )
        from opensandbox.api.lifecycle.models.network_rule_action import (
            NetworkRuleAction,
        )
        from opensandbox.api.lifecycle.models.resource_limits import ResourceLimits
        from opensandbox.api.lifecycle.types import UNSET

        # Convert env dict to API model
        api_env = UNSET
        if env:
            api_env = CreateSandboxRequestEnv.from_dict(env)

        # Convert metadata dict to API model
        api_metadata = UNSET
        if metadata:
            api_metadata = CreateSandboxRequestMetadata.from_dict(metadata)

        # Convert resource limits dict to API model
        api_resource_limits = ResourceLimits.from_dict(resource)

        api_network_policy = UNSET
        if network_policy is not None:
            if not isinstance(network_policy, NetworkPolicy):
                raise TypeError(
                    "network_policy must be a NetworkPolicy or None, "
                    f"got {type(network_policy).__name__}"
                )
            api_default_action = UNSET
            if network_policy.default_action:
                api_default_action = NetworkPolicyDefaultAction(
                    network_policy.default_action
                )

            api_egress = UNSET
            if network_policy.egress is not None:
                api_egress = [
                    ApiNetworkRule(
                        action=NetworkRuleAction(rule.action),
                        target=rule.target,
                    )
                    for rule in network_policy.egress
                ]

            api_network_policy = ApiNetworkPolicy(
                default_action=api_default_action,
                egress=api_egress,
            )

        api_extensions = (
            CreateSandboxRequestExtensions.from_dict(extensions) if extensions else UNSET
        )

        # Convert volumes to API model
        api_volumes = UNSET
        if volumes is not None and len(volumes) > 0:
            api_volumes = [
                SandboxModelConverter.to_api_volume(v) for v in volumes
            ]

        request = CreateSandboxRequest(
            image=SandboxModelConverter.to_api_image_spec(spec),
            entrypoint=entrypoint,
            env=api_env,
            metadata=api_metadata,
            resource_limits=api_resource_limits,
            network_policy=api_network_policy,
            extensions=api_extensions,
            volumes=api_volumes,
        )
        if timeout is not None:
            request.timeout = int(timeout.total_seconds())
        return request

    @staticmethod
    def to_api_renew_request(
        new_expiration_time: datetime,
    ) -> RenewSandboxExpirationRequest:
        """Convert datetime to API renew request."""
        from opensandbox.api.lifecycle.models.renew_sandbox_expiration_request import (
            RenewSandboxExpirationRequest,
        )

        # Ensure timezone-aware datetime for unambiguous serialization.
        # If a naive datetime is provided, treat it as UTC.
        if new_expiration_time.tzinfo is None:
            new_expiration_time = new_expiration_time.replace(tzinfo=timezone.utc)

        return RenewSandboxExpirationRequest(
            expires_at=new_expiration_time,
        )

    @staticmethod
    def to_sandbox_renew_response(
        api_response: RenewSandboxExpirationResponse,
    ) -> SandboxRenewResponse:
        """
        Convert API RenewSandboxExpirationResponse to domain SandboxRenewResponse.

        Note: We intentionally keep the public SDK surface using domain models instead of the
        generated OpenAPI client models.
        """

        if not isinstance(api_response, RenewSandboxExpirationResponse):
            raise TypeError(
                f"Expected RenewSandboxExpirationResponse, got {type(api_response).__name__}"
            )

        return SandboxRenewResponse(expires_at=api_response.expires_at)

    @staticmethod
    def to_sandbox_create_response(
        api_response: CreateSandboxResponse,
    ) -> SandboxCreateResponse:
        """Convert API CreateSandboxResponse to domain SandboxCreateResponse."""
        from opensandbox.models.sandboxes import SandboxCreateResponse

        return SandboxCreateResponse(
            id=str(api_response.id)
        )

    @staticmethod
    def to_sandbox_info(api_sandbox: Sandbox) -> SandboxInfo:
        """Convert API Sandbox to domain SandboxInfo."""
        from opensandbox.api.lifecycle.types import Unset
        from opensandbox.models.sandboxes import (
            SandboxImageAuth,
            SandboxImageSpec,
            SandboxInfo,
        )

        domain_image_spec = None
        if hasattr(api_sandbox, "image") and not isinstance(api_sandbox.image, Unset):
            auth = None
            if hasattr(api_sandbox.image, "auth") and not isinstance(
                api_sandbox.image.auth, Unset
            ):
                auth_obj = api_sandbox.image.auth
                username_val = getattr(auth_obj, "username", None)
                password_val = getattr(auth_obj, "password", None)
                if isinstance(username_val, str) and isinstance(password_val, str):
                    auth = SandboxImageAuth(username=username_val, password=password_val)
            domain_image_spec = SandboxImageSpec(
                image=api_sandbox.image.uri,
                auth=auth,
            )

        metadata: dict[str, str] = {}
        if hasattr(api_sandbox, "metadata") and not isinstance(api_sandbox.metadata, Unset):
            metadata_obj = api_sandbox.metadata
            if hasattr(metadata_obj, "additional_properties") and not isinstance(
                getattr(metadata_obj, "additional_properties", None), Unset
            ):
                props = metadata_obj.additional_properties
                if isinstance(props, dict):
                    metadata = dict(props)
            elif isinstance(metadata_obj, dict):
                metadata = metadata_obj

        expires_at = api_sandbox.expires_at
        if isinstance(expires_at, Unset):
            expires_at = None

        return SandboxInfo(
            id=api_sandbox.id,
            status=SandboxModelConverter._convert_sandbox_status(api_sandbox.status),
            image=domain_image_spec,
            created_at=api_sandbox.created_at,
            expires_at=expires_at,
            entrypoint=api_sandbox.entrypoint,
            metadata=metadata,
        )

    @staticmethod
    def to_paged_sandbox_infos(
        api_response: ListSandboxesResponse,
    ) -> PagedSandboxInfos:
        """Convert API ListSandboxesResponse to domain PagedSandboxInfos."""
        from opensandbox.models.sandboxes import PagedSandboxInfos

        items = api_response.items if hasattr(api_response, "items") else []

        return PagedSandboxInfos(
            sandbox_infos=[SandboxModelConverter.to_sandbox_info(s) for s in items],
            pagination=SandboxModelConverter._convert_pagination_info(
                api_response.pagination
            ),
        )

    @staticmethod
    def to_sandbox_endpoint(api_endpoint: Endpoint) -> SandboxEndpoint:
        """Convert API Endpoint to domain SandboxEndpoint."""
        from opensandbox.api.lifecycle.types import Unset
        from opensandbox.models.sandboxes import SandboxEndpoint

        headers: dict[str, str] = {}
        if not isinstance(api_endpoint.headers, Unset):
            headers = dict(api_endpoint.headers.additional_properties)
        return SandboxEndpoint(
            endpoint=api_endpoint.endpoint,
            headers=headers,
        )

    @staticmethod
    def _convert_sandbox_status(
        api_status: ApiSandboxStatus | None,
    ) -> SandboxStatus:
        """Convert API SandboxStatus to domain SandboxStatus."""
        from datetime import datetime

        from opensandbox.api.lifecycle.types import Unset
        from opensandbox.models.sandboxes import SandboxStatus

        if api_status is None:
            return SandboxStatus(
                state="Unknown",
                reason=None,
                message=None,
                last_transition_at=None,
            )

        reason: str | None = None
        if hasattr(api_status, "reason"):
            reason_val = api_status.reason
            if isinstance(reason_val, str):
                reason = reason_val

        message: str | None = None
        if hasattr(api_status, "message"):
            message_val = api_status.message
            if isinstance(message_val, str):
                message = message_val

        last_transition_at: datetime | None = None
        if hasattr(api_status, "last_transition_at"):
            lta_val = api_status.last_transition_at
            if isinstance(lta_val, datetime):
                last_transition_at = lta_val
            elif isinstance(lta_val, Unset) or lta_val is None:
                last_transition_at = None

        return SandboxStatus(
            state=api_status.state,
            reason=reason,
            message=message,
            last_transition_at=last_transition_at,
        )

    @staticmethod
    def _convert_pagination_info(
        api_pagination: ApiPaginationInfo | None,
    ) -> PaginationInfo:
        """Convert API PaginationInfo to domain PaginationInfo."""
        from opensandbox.models.sandboxes import PaginationInfo

        if api_pagination is None:
            return PaginationInfo(
                page=1,
                page_size=10,
                total_pages=0,
                total_items=0,
                has_next_page=False,
            )

        return PaginationInfo(
            page=api_pagination.page or 1,
            page_size=api_pagination.page_size or 10,
            total_pages=api_pagination.total_pages or 0,
            total_items=api_pagination.total_items or 0,
            has_next_page=api_pagination.has_next_page or False,
        )
