// Code generated by MockGen. DO NOT EDIT.
// Source: allocator.go

// Package controller is a generated GoMock package.
package controller

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	v1alpha1 "github.com/alibaba/OpenSandbox/sandbox-k8s/apis/sandbox/v1alpha1"
)

// MockAllocationStore is a mock of AllocationStore interface.
type MockAllocationStore struct {
	ctrl     *gomock.Controller
	recorder *MockAllocationStoreMockRecorder
}

// MockAllocationStoreMockRecorder is the mock recorder for MockAllocationStore.
type MockAllocationStoreMockRecorder struct {
	mock *MockAllocationStore
}

// NewMockAllocationStore creates a new mock instance.
func NewMockAllocationStore(ctrl *gomock.Controller) *MockAllocationStore {
	mock := &MockAllocationStore{ctrl: ctrl}
	mock.recorder = &MockAllocationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllocationStore) EXPECT() *MockAllocationStoreMockRecorder {
	return m.recorder
}

// GetAllocation mocks base method.
func (m *MockAllocationStore) GetAllocation(ctx context.Context, pool *v1alpha1.Pool) (*PoolAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllocation", ctx, pool)
	ret0, _ := ret[0].(*PoolAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllocation indicates an expected call of GetAllocation.
func (mr *MockAllocationStoreMockRecorder) GetAllocation(ctx, pool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllocation", reflect.TypeOf((*MockAllocationStore)(nil).GetAllocation), ctx, pool)
}

// SetAllocation mocks base method.
func (m *MockAllocationStore) SetAllocation(ctx context.Context, pool *v1alpha1.Pool, allocation *PoolAllocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAllocation", ctx, pool, allocation)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAllocation indicates an expected call of SetAllocation.
func (mr *MockAllocationStoreMockRecorder) SetAllocation(ctx, pool, allocation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAllocation", reflect.TypeOf((*MockAllocationStore)(nil).SetAllocation), ctx, pool, allocation)
}

// MockAllocationSyncer is a mock of AllocationSyncer interface.
type MockAllocationSyncer struct {
	ctrl     *gomock.Controller
	recorder *MockAllocationSyncerMockRecorder
}

// MockAllocationSyncerMockRecorder is the mock recorder for MockAllocationSyncer.
type MockAllocationSyncerMockRecorder struct {
	mock *MockAllocationSyncer
}

// NewMockAllocationSyncer creates a new mock instance.
func NewMockAllocationSyncer(ctrl *gomock.Controller) *MockAllocationSyncer {
	mock := &MockAllocationSyncer{ctrl: ctrl}
	mock.recorder = &MockAllocationSyncerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllocationSyncer) EXPECT() *MockAllocationSyncerMockRecorder {
	return m.recorder
}

// GetAllocation mocks base method.
func (m *MockAllocationSyncer) GetAllocation(ctx context.Context, sandbox *v1alpha1.BatchSandbox) (*SandboxAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllocation", ctx, sandbox)
	ret0, _ := ret[0].(*SandboxAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllocation indicates an expected call of GetAllocation.
func (mr *MockAllocationSyncerMockRecorder) GetAllocation(ctx, sandbox interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllocation", reflect.TypeOf((*MockAllocationSyncer)(nil).GetAllocation), ctx, sandbox)
}

// GetRelease mocks base method.
func (m *MockAllocationSyncer) GetRelease(ctx context.Context, sandbox *v1alpha1.BatchSandbox) (*AllocationRelease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelease", ctx, sandbox)
	ret0, _ := ret[0].(*AllocationRelease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelease indicates an expected call of GetRelease.
func (mr *MockAllocationSyncerMockRecorder) GetRelease(ctx, sandbox interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelease", reflect.TypeOf((*MockAllocationSyncer)(nil).GetRelease), ctx, sandbox)
}

// SetAllocation mocks base method.
func (m *MockAllocationSyncer) SetAllocation(ctx context.Context, sandbox *v1alpha1.BatchSandbox, allocation *SandboxAllocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAllocation", ctx, sandbox, allocation)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAllocation indicates an expected call of SetAllocation.
func (mr *MockAllocationSyncerMockRecorder) SetAllocation(ctx, sandbox, allocation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAllocation", reflect.TypeOf((*MockAllocationSyncer)(nil).SetAllocation), ctx, sandbox, allocation)
}

// MockAllocator is a mock of Allocator interface.
type MockAllocator struct {
	ctrl     *gomock.Controller
	recorder *MockAllocatorMockRecorder
}

// MockAllocatorMockRecorder is the mock recorder for MockAllocator.
type MockAllocatorMockRecorder struct {
	mock *MockAllocator
}

// NewMockAllocator creates a new mock instance.
func NewMockAllocator(ctrl *gomock.Controller) *MockAllocator {
	mock := &MockAllocator{ctrl: ctrl}
	mock.recorder = &MockAllocatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllocator) EXPECT() *MockAllocatorMockRecorder {
	return m.recorder
}

// Schedule mocks base method.
func (m *MockAllocator) Schedule(ctx context.Context, spec *AllocSpec) (*AllocStatus, []SandboxSyncInfo, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule", ctx, spec)
	ret0, _ := ret[0].(*AllocStatus)
	ret1, _ := ret[1].([]SandboxSyncInfo)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Schedule indicates an expected call of Schedule.
func (mr *MockAllocatorMockRecorder) Schedule(ctx, spec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockAllocator)(nil).Schedule), ctx, spec)
}

// GetPoolAllocation mocks base method.
func (m *MockAllocator) GetPoolAllocation(ctx context.Context, pool *v1alpha1.Pool) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPoolAllocation", ctx, pool)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPoolAllocation indicates an expected call of GetPoolAllocation.
func (mr *MockAllocatorMockRecorder) GetPoolAllocation(ctx, pool interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPoolAllocation", reflect.TypeOf((*MockAllocator)(nil).GetPoolAllocation), ctx, pool)
}

func (m *MockAllocator) PersistPoolAllocation(ctx context.Context, pool *v1alpha1.Pool, status *AllocStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistPoolAllocation", ctx, pool, status)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockAllocatorMockRecorder) PersistPoolAllocation(ctx, pool, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistPoolAllocation", reflect.TypeOf((*MockAllocator)(nil).PersistPoolAllocation), ctx, pool, status)
}

func (m *MockAllocator) SyncSandboxAllocation(ctx context.Context, sandbox *v1alpha1.BatchSandbox, pods []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncSandboxAllocation", ctx, sandbox, pods)
	ret0, _ := ret[0].(error)
	return ret0
}

func (mr *MockAllocatorMockRecorder) SyncSandboxAllocation(ctx, sandbox, pods interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncSandboxAllocation", reflect.TypeOf((*MockAllocator)(nil).SyncSandboxAllocation), ctx, sandbox, pods)
}
